import { User, KYCDocument } from '@/types/user'

// Mock user data
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1 234-567-8900',
    signupDate: new Date('2024-01-15'),
    lastLogin: new Date('2024-12-02'),
    status: 'active',
    kycStatus: 'verified',
    riskScore: 25,
    totalOrders: 45,
    totalSpent: 185000,
    tags: ['premium', 'frequent-buyer'],
    address: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zip: '10001',
      country: 'USA',
    },
    devices: [
      {
        id: 'd1',
        deviceType: 'iPhone 15 Pro',
        appVersion: '2.5.1',
        lastIP: '192.168.1.100',
        lastSeen: new Date('2024-12-02'),
      },
    ],
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+1 234-567-8901',
    signupDate: new Date('2024-03-20'),
    lastLogin: new Date('2024-12-01'),
    status: 'active',
    kycStatus: 'pending',
    riskScore: 15,
    totalOrders: 28,
    totalSpent: 142000,
    tags: ['new-customer'],
    address: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90001',
      country: 'USA',
    },
  },
  {
    id: '3',
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    phone: '+1 234-567-8902',
    signupDate: new Date('2024-06-10'),
    lastLogin: new Date('2024-11-30'),
    status: 'blocked',
    kycStatus: 'rejected',
    riskScore: 85,
    totalOrders: 12,
    totalSpent: 67000,
    tags: ['fraud-alert', 'high-risk'],
    address: {
      street: '789 Elm St',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      country: 'USA',
    },
  },
  {
    id: '4',
    name: 'Alice Williams',
    email: 'alice.w@example.com',
    phone: '+1 234-567-8903',
    signupDate: new Date('2024-08-05'),
    lastLogin: new Date('2024-12-02'),
    status: 'active',
    kycStatus: 'verified',
    riskScore: 10,
    totalOrders: 67,
    totalSpent: 675000,
    tags: ['vip', 'premium'],
  },
  {
    id: '5',
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    phone: '+1 234-567-8904',
    signupDate: new Date('2024-09-12'),
    lastLogin: null,
    status: 'pending',
    kycStatus: 'pending',
    riskScore: 5,
    totalOrders: 2,
    totalSpent: 9000,
    tags: [],
  },
]

export const mockKYCDocuments: KYCDocument[] = [
  {
    id: 'kyc1',
    userId: '1',
    type: 'aadhaar',
    documentNumber: '1234-5678-9012',
    status: 'verified',
    fileUrl: '/documents/kyc1.pdf',
    uploadedAt: new Date('2024-01-16'),
    verifiedAt: new Date('2024-01-17'),
  },
  {
    id: 'kyc2',
    userId: '2',
    type: 'pan',
    documentNumber: 'ABCDE1234F',
    status: 'pending',
    fileUrl: '/documents/kyc2.pdf',
    uploadedAt: new Date('2024-03-21'),
  },
  {
    id: 'kyc3',
    userId: '3',
    type: 'driving_license',
    documentNumber: 'DL123456789',
    status: 'rejected',
    fileUrl: '/documents/kyc3.pdf',
    uploadedAt: new Date('2024-06-11'),
    rejectionReason: 'Document expired',
  },
]
